[package]
org = "ballerinai"
name = "transaction"
version = "@toml.version@"
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
artifactId = "transaction"
version = "@project.version@"
path = "../transaction-native/build/libs/transaction-native-@project.version@.jar"
groupId = "ballerina"
