[package]
org = "ballerinai"
name = "transaction"
version = "0.0.0"
distribution = "2201.9.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
artifactId = "transaction"
version = "1.9.1-TR"
path = "../transaction-native/build/libs/transaction-native-1.9.1-TR.jar"
groupId = "ballerina"
