[package]
org = "ballerinai"
name = "transaction"
version = "0.0.0"
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
artifactId = "transaction"
version = "1.11.0-SNAPSHOT"
path = "../transaction-native/build/libs/transaction-native-1.11.0-SNAPSHOT.jar"
groupId = "ballerina"
