[package]
org = "ballerinai"
name = "transaction"
version = "0.0.0"

[[platform.java11.dependency]]
artifactId = "transaction"
version = "1.3.0"
path = "../transaction-native/build/libs/transaction-native-1.3.0.jar"
groupId = "ballerina"
