[package]
org = "ballerinai"
name = "transaction"
version = "0.0.0"

[[platform.java11.dependency]]
artifactId = "transaction"
version = "1.0.19-SNAPSHOT"
path = "../transaction-native/build/libs/transaction-native-1.0.19-SNAPSHOT.jar"
groupId = "ballerina"
