[package]
org = "ballerinai"
name = "transaction_negative_tests"
version = "1.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../transaction-native/build/libs/transaction-native-1.11.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "transaction"
version = "1.11.0-SNAPSHOT"

[[platform.java21.dependency]]
path = "../transaction-test-utils/build/libs/transaction-test-utils-1.11.0-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.transaction"
scope = "testOnly"
artifactId = "transaction"
version = "1.11.0-SNAPSHOT"

[[platform.java21.dependency]]
path = "./lib/io-native-1.7.0-20241121-173300-0fbd5d4.jar"
groupId = "org.ballerinalang"
artifactId = "io-native"
version = "1.7.0-20241121-173300-0fbd5d4"
